from django.db import models
from statsonice.models.models_validator import EnumValidator

class Category(models.Model):
    CATEGORY_CHOICES = (
        ('MEN', 'Men'),
        ('LADIES', 'Ladies'),
        ('PAIRS', 'Pairs'),
        ('DANCE', 'Ice Dance'),
    )
    category = models.CharField(max_length = 10,
                                choices = CATEGORY_CHOICES,
                                default = '',
                                primary_key=True)

    class Meta:
        app_label = 'statsonice'
    def __unicode__(self):
        return u'(Category %s)' % (self.category)
    def clean(self):
        EnumValidator.validate_enum(self.category, Category.CATEGORY_CHOICES)
    def save(self, *args, **kwargs):
        self.full_clean()
        super(Category, self).save(*args, **kwargs)


class Component(models.Model):
    COMPONENT_CHOICES = (
        ('SS', 'Skating Skills'),
        ('TR', 'Transitions Transition/Linking Footwork Transition / Linking Footwork Transitions/Linking Footwork/Movements'),   # Transitions/Linking Footwork
        ('PE', 'Performance/Execution Performance / Execution'),  # Performance/Execution
        ('PF', 'Performance'),
        ('CH', 'Choreography/Composition Choreography / Composition Composition/Choreography Composition / Choreography'), # Choreography/Composition
        ('IN', 'Interpretation'),
        ('CC', 'Choreography'),
        ('IT', 'Interpretation/Timing Interpretation / Timing'),
        ('TI', 'Timing'),
        ('MO', 'Footwork/Movement Footwork / Movement Footwork/Movements Footwork / Movements Linking Footwork/Movement Linking Footwork / Movement'),
    )
    component = models.CharField(max_length = 10,
                                 choices = COMPONENT_CHOICES,
                                 default = '',
                                 primary_key=True)
    class Meta:
        app_label = 'statsonice'
    def __unicode__(self):
        return u'(Component %s)' % (self.component)
    def clean(self):
        EnumValidator.validate_enum(self.component, Component.COMPONENT_CHOICES)
    def save(self, *args, **kwargs):
        self.full_clean()
        super(Component, self).save(*args, **kwargs)


class Flag(models.Model):
    FLAG_CHOICES = (
        ('OL', 'Outlier'),
        ('PC', 'Perfect Consensus'),
        ('NC', 'No Consensus'),
        ('TO', 'Three and One')
    )

    flag = models.CharField(max_length = 2,
                            choices = FLAG_CHOICES,
                            default = 'NC',
                            primary_key = True)

    class Meta:
        app_label = 'statsonice'
    def __unicode__(self):
        return u'(Flag %s)' % (self.flag)

    # TODO: add clean and save methods, and validators


class Level(models.Model):
    LEVEL_CHOICES = (
        ('', ''),
        ('NO', 'No Test'),
        ('PP', 'Pre-Preliminary'),
        ('PR', 'Preliminary'),
        ('PJ', 'Pre-Juvenile'),
        ('JUV', 'Juvenile'),
        ('INT', 'Intermediate'),
        ('NOV', 'Novice'),
        ('JR', 'Junior'),
        ('SR', 'Senior'),
    )
    level = models.CharField(max_length = 10,
                             choices = LEVEL_CHOICES,
                             default = '',
                             primary_key=True,
                             blank=True)

    class Meta:
        app_label = 'statsonice'
    def __unicode__(self):
        return u'(Level %s)' % (self.level)
    def clean(self):
        EnumValidator.validate_enum(self.level, Level.LEVEL_CHOICES)
    def save(self, *args, **kwargs):
        self.full_clean()
        super(Level, self).save(*args, **kwargs)


# TODO: resolve fact that definition of < changed
# before October 2010 < changed base value from triple to double, e.g.
# After October 2010, < replaced by <<
# After October 2010, < makes jumps worth 70% of base value
class Modifier(models.Model):
    MODIFIES_ONE = (
        ('<', 'Under-rotated jump'),
        ('<<', 'Downgraded jump'),
    )
    MODIFIES_AFTER = (
        ('SEQ', 'Jump sequence'),
        ('COMBO', 'Invalid combination'),
        ('TRANS', 'Dance Transition'),
        ('kpNNN', 'Key Point - NO, NO, NO'),
        ('kpYNN', 'Key Point - YES, NO, NO'),
        ('kpNYN', 'Key Point - NO, YES, NO'),
        ('kpNNY', 'Key Point - NO, NO, YES'),
        ('kpYYN', 'Key Point - YES, YES, NO'),
        ('kpYNY', 'Key Point - YES, NO, YES'),
        ('kpNYY', 'Key Point - NO, YES, YES'),
        ('kpYYY', 'Key Point - YES, YES, YES'),
        ('kpYTT', 'Key Point - YES, NO, NO'),
        ('kpTYT', 'Key Point - NO, YES, NO'),
        ('kpTTY', 'Key Point - NO, NO, YES'),
        ('kpYYT', 'Key Point - YES, YES, NO'),
        ('kpYTY', 'Key Point - YES, NO, YES'),
        ('kpTYY', 'Key Point - NO, YES, YES'),
        ('kpTNN', 'Key Point - YES, NO, NO'),
        ('kpNTN', 'Key Point - NO, YES, NO'),
        ('kpNNT', 'Key Point - NO, NO, YES'),
        ('kpTTN', 'Key Point - YES, YES, NO'),
        ('kpTNT', 'Key Point - YES, NO, YES'),
        ('kpNTT', 'Key Point - NO, YES, YES'),
        ('kpTTT', 'Key Point - YES, YES, YES'),
        ('kpTNY', 'Key Point - YES, NO, YES'),
        ('kpTYN', 'Key Point - NO, YES, YES'),
        ('kpNYT', 'Key Point - YES, YES, YES'),
        ('kpNTY', 'Key Point - YES, NO, YES'),
        ('kpYTN', 'Key Point - NO, YES, YES'),
        ('kpTNY', 'Key Point - YES, YES, YES'),
    )

    MODIFIES_ALL = (
        ('*', 'Invalid element'),
        ('!', 'Jump take off with wrong edge (short)'),
        ('e', 'Jump take off with wrong edge'),
        ('x', 'Credit for highlight distribution'),
    )

    MODIFIER_CHOICES = MODIFIES_ONE + MODIFIES_AFTER + MODIFIES_ALL

    modifier = models.CharField(max_length = 10,
                                choices = MODIFIER_CHOICES,
                                default = '',
                                primary_key=True)
    class Meta:
        app_label = 'statsonice'
    def __unicode__(self):
        return u'(Modifier %s)' % (self.modifier)
    def clean(self):
        EnumValidator.validate_enum(self.modifier, Modifier.MODIFIER_CHOICES)
    def save(self, *args, **kwargs):
        self.full_clean()
        super(Modifier, self).save(*args, **kwargs)



class Segment(models.Model):
    SEGMENT_CHOICES = (
        ('', ''),
        ('SP', 'Short Program'),
        ('FS', 'Free Skating'),
        ('CD', 'Compulsory Dance'),
        ('OD', 'Original Dance'),
        ('FD', 'Free Dance'),
        ('SD', 'Short Dance'),
    )
    segment = models.CharField(max_length = 10,
                               choices = SEGMENT_CHOICES,
                               default = '',
                               primary_key=True,
                               blank=True)
    class Meta:
        app_label = 'statsonice'
    def __unicode__(self):
        return u'(Segment %s)' % (self.segment)
    def clean(self):
        EnumValidator.validate_enum(self.segment, Segment.SEGMENT_CHOICES)
    def save(self, *args, **kwargs):
        self.full_clean()
        super(Segment, self).save(*args, **kwargs)


# Base element class; manipulated by Element class to allow modifiers and combinations element class
#
class BaseElement(models.Model):
    BASE_ELEMENT_CHOICES = (
        ('', ''),
        ('T', 'Toeloop'),
        ('S', 'Salchow'),
        ('Lo', 'Loop'),
        ('F', 'Flip'),
        ('Lz', 'Lutz'),
        ('A', 'Axel'),
        ('1T', 'Single Toeloop'),
        ('1S', 'Single Salchow'),
        ('1Lo', 'Single Loop'),
        ('1F', 'Single Flip'),
        ('1Lz', 'Single Lutz'),
        ('1A', 'Single Axel'),
        ('2T', 'Double Toeloop'),
        ('2S', 'Double Salchow'),
        ('2Lo', 'Double Loop'),
        ('2F', 'Double Flip'),
        ('2Lz', 'Double Lutz'),
        ('2A', 'Double Axel'),
        ('3T', 'Triple Toeloop'),
        ('3S', 'Triple Salchow'),
        ('3Lo', 'Triple Loop'),
        ('3F', 'Triple Flip'),
        ('3Lz', 'Triple Lutz'),
        ('3A', 'Triple Axel'),
        ('4T', 'Quadruple Toeloop'),
        ('4S', 'Quadruple Salchow'),
        ('4Lo', 'Quadruple Loop'),
        ('4F', 'Quadruple Flip'),
        ('4Lz', 'Quadruple Lutz'),
        ('4A', 'Quadruple Axel'),
        ('USp', 'Upright'),
        ('USpB', 'Upright Level B'),
        ('USp1', 'Upright Level 1'),
        ('USp2', 'Upright Level 2'),
        ('USp3', 'Upright Level 3'),
        ('USp4', 'Upright Level 4'),
        ('LSp', 'Layback'),
        ('LSpB', 'Layback Level B'),
        ('LSp1', 'Layback Level 1'),
        ('LSp2', 'Layback Level 2'),
        ('LSp3', 'Layback Level 3'),
        ('LSp4', 'Layback Level 4'),
        ('CSp', 'Camel'),
        ('CSpB', 'Camel Level B'),
        ('CSp1', 'Camel Level 1'),
        ('CSp2', 'Camel Level 2'),
        ('CSp3', 'Camel Level 3'),
        ('CSp4', 'Camel Level 4'),
        ('SSp', 'Sit'),
        ('SSpB', 'Sit Level B'),
        ('SSp1', 'Sit Level 1'),
        ('SSp2', 'Sit Level 2'),
        ('SSp3', 'Sit Level 3'),
        ('SSp4', 'Sit Level 4'),
        ('FUSp', 'Flying Upright'),
        ('FUSpB', 'Flying Upright Level B'),
        ('FUSp1', 'Flying Upright Level 1'),
        ('FUSp2', 'Flying Upright Level 2'),
        ('FUSp3', 'Flying Upright Level 3'),
        ('FUSp4', 'Flying Upright Level 4'),
        ('FLSp', 'Flying Layback'),
        ('FLSpB', 'Flying Layback Level B'),
        ('FLSp1', 'Flying Layback Level 1'),
        ('FLSp2', 'Flying Layback Level 2'),
        ('FLSp3', 'Flying Layback Level 3'),
        ('FLSp4', 'Flying Layback Level 4'),
        ('FCSp', 'Flying Camel'),
        ('FCSpB', 'Flying Camel Level B'),
        ('FCSp1', 'Flying Camel Level 1'),
        ('FCSp2', 'Flying Camel Level 2'),
        ('FCSp3', 'Flying Camel Level 3'),
        ('FCSp4', 'Flying Camel Level 4'),
        ('FSSp', 'Flying Sit'),
        ('FSSpB', 'Flying Sit Level B'),
        ('FSSp1', 'Flying Sit Level 1'),
        ('FSSp2', 'Flying Sit Level 2'),
        ('FSSp3', 'Flying Sit Level 3'),
        ('FSSp4', 'Flying Sit Level 4'),
        ('CUSp', 'Change Upright'),
        ('CUSpB', 'Change Upright Level B'),
        ('CUSp1', 'Change Upright Level 1'),
        ('CUSp2', 'Change Upright Level 2'),
        ('CUSp3', 'Change Upright Level 3'),
        ('CUSp4', 'Change Upright Level 4'),
        ('CLSp', 'Change Layback'),
        ('CLSpB', 'Change Layback Level B'),
        ('CLSp1', 'Change Layback Level 1'),
        ('CLSp2', 'Change Layback Level 2'),
        ('CLSp3', 'Change Layback Level 3'),
        ('CLSp4', 'Change Layback Level 4'),
        ('CCSp', 'Change Camel'),
        ('CCSpB', 'Change Camel Level B'),
        ('CCSp1', 'Change Camel Level 1'),
        ('CCSp2', 'Change Camel Level 2'),
        ('CCSp3', 'Change Camel Level 3'),
        ('CCSp4', 'Change Camel Level 4'),
        ('CSSp', 'Change Sit'),
        ('CSSpB', 'Change Sit Level B'),
        ('CSSp1', 'Change Sit Level 1'),
        ('CSSp2', 'Change Sit Level 2'),
        ('CSSp3', 'Change Sit Level 3'),
        ('CSSp4', 'Change Sit Level 4'),
        ('CoSp', 'Change Combination'),
        ('CoSpB', 'Change Combination Level B'),
        ('CoSp1', 'Change Combination Level 1'),
        ('CoSp2', 'Change Combination Level 2'),
        ('CoSp3', 'Change Combination Level 3'),
        ('CoSp4', 'Change Combination Level 4'),
        ('CCoSp', 'Change Foot Combination'),
        ('CCoSpB', 'Change Foot Combination Level B'),
        ('CCoSp1', 'Change Foot Combination Level 1'),
        ('CCoSp2', 'Change Foot Combination Level 2'),
        ('CCoSp3', 'Change Foot Combination Level 3'),
        ('CCoSp4', 'Change Foot Combination Level 4'),
        ('FCUSp', 'Flying Change Upright'),
        ('FCUSpB', 'Flying Change Upright Level B'),
        ('FCUSp1', 'Flying Change Upright Level 1'),
        ('FCUSp2', 'Flying Change Upright Level 2'),
        ('FCUSp3', 'Flying Change Upright Level 3'),
        ('FCUSp4', 'Flying Change Upright Level 4'),
        ('FCLSp', 'Flying Change Layback'),
        ('FCLSpB', 'Flying Change Layback Level B'),
        ('FCLSp1', 'Flying Change Layback Level 1'),
        ('FCLSp2', 'Flying Change Layback Level 2'),
        ('FCLSp3', 'Flying Change Layback Level 3'),
        ('FCLSp4', 'Flying Change Layback Level 4'),
        ('FCCSp', 'Flying Change Camel'),
        ('FCCSpB', 'Flying Change Camel Level B'),
        ('FCCSp1', 'Flying Change Camel Level 1'),
        ('FCCSp2', 'Flying Change Camel Level 2'),
        ('FCCSp3', 'Flying Change Camel Level 3'),
        ('FCCSp4', 'Flying Change Camel Level 4'),
        ('FCSSp', 'Flying Change Sit'),
        ('FCSSpB', 'Flying Change Sit Level B'),
        ('FCSSp1', 'Flying Change Sit Level 1'),
        ('FCSSp2', 'Flying Change Sit Level 2'),
        ('FCSSp3', 'Flying Change Sit Level 3'),
        ('FCSSp4', 'Flying Change Sit Level 4'),
        ('FCoSp', 'Flying Change Combination'),
        ('FCoSpB', 'Flying Change Combination Level B'),
        ('FCoSp1', 'Flying Change Combination Level 1'),
        ('FCoSp2', 'Flying Change Combination Level 2'),
        ('FCoSp3', 'Flying Change Combination Level 3'),
        ('FCoSp4', 'Flying Change Combination Level 4'),
        ('FCCoSp', 'Flying Change Foot Combination'),
        ('FCCoSpB', 'Flying Change Foot Combination Level B'),
        ('FCCoSp1', 'Flying Change Foot Combination Level 1'),
        ('FCCoSp2', 'Flying Change Foot Combination Level 2'),
        ('FCCoSp3', 'Flying Change Foot Combination Level 3'),
        ('FCCoSp4', 'Flying Change Foot Combination Level 4'),
        ('StSq', 'Step Sequence'),
        ('StSqB', 'Step Sequence Level B'),
        ('StSq1', 'Step Sequence Level 1'),
        ('StSq2', 'Step Sequence Level 2'),
        ('StSq3', 'Step Sequence Level 3'),
        ('StSq4', 'Step Sequence Level 4'),
        ('SlSt', 'Straight Line Step Sequence'),
        ('SlStB', 'Straight Line Step Sequence Level B'),
        ('SlSt1', 'Straight Line Step Sequence Level 1'),
        ('SlSt2', 'Straight Line Step Sequence Level 2'),
        ('SlSt3', 'Straight Line Step Sequence Level 3'),
        ('SlSt4', 'Straight Line Step Sequence Level 4'),
        ('CiSt', 'Circular Step Sequence'),
        ('CiStB', 'Circular Step Sequence Level B'),
        ('CiSt1', 'Circular Step Sequence Level 1'),
        ('CiSt2', 'Circular Step Sequence Level 2'),
        ('CiSt3', 'Circular Step Sequence Level 3'),
        ('CiSt4', 'Circular Step Sequence Level 4'),
        ('SeSt', 'Serpentine Step Sequence'),
        ('SeStB', 'Serpentine Step Sequence Level B'),
        ('SeSt1', 'Serpentine Step Sequence Level 1'),
        ('SeSt2', 'Serpentine Step Sequence Level 2'),
        ('SeSt3', 'Serpentine Step Sequence Level 3'),
        ('SeSt4', 'Serpentine Step Sequence Level 4'),
        ('ChSq', 'Choreographic Sequence'),
        ('ChSq1', 'Choreographic Sequence'),
        ('SpSq', 'Spiral Sequence'),
        ('SpSqB', 'Spiral Sequence Level B'),
        ('SpSq1', 'Spiral Sequence Level 1'),
        ('SpSq2', 'Spiral Sequence Level 2'),
        ('SpSq3', 'Spiral Sequence Level 3'),
        ('SpSq4', 'Spiral Sequence Level 4'),
        ('1Li', 'Group 1 Lift'),
        ('1LiB', 'Group 1 Level B Lift'),
        ('1Li1', 'Group 1 Level 1 Lift'),
        ('1Li2', 'Group 1 Level 2 Lift'),
        ('1Li3', 'Group 1 Level 3 Lift'),
        ('1Li4', 'Group 1 Level 4 Lift'),
        ('2Li', 'Group 2 Lift'),
        ('2LiB', 'Group 2 Level B Lift'),
        ('2Li1', 'Group 2 Level 1 Lift'),
        ('2Li2', 'Group 2 Level 2 Lift'),
        ('2Li3', 'Group 2 Level 3 Lift'),
        ('2Li4', 'Group 2 Level 4 Lift'),
        ('3Li', 'Group 3 Lift'),
        ('3LiB', 'Group 3 Level B Lift'),
        ('3Li1', 'Group 3 Level 1 Lift'),
        ('3Li2', 'Group 3 Level 2 Lift'),
        ('3Li3', 'Group 3 Level 3 Lift'),
        ('3Li4', 'Group 3 Level 4 Lift'),
        ('4Li', 'Group 4 Lift'),
        ('4LiB', 'Group 4 Level B Lift'),
        ('4Li1', 'Group 4 Level 1 Lift'),
        ('4Li2', 'Group 4 Level 2 Lift'),
        ('4Li3', 'Group 4 Level 3 Lift'),
        ('4Li4', 'Group 4 Level 4 Lift'),
        ('5TLi', 'Group 5 Toe in Lasso Lift'),
        ('5TLiB', 'Group 5 Toe in Lasso Lift Level B'),
        ('5TLi1', 'Group 5 Toe in Lasso Lift Level 1'),
        ('5TLi2', 'Group 5 Toe in Lasso Lift Level 2'),
        ('5TLi3', 'Group 5 Toe in Lasso Lift Level 3'),
        ('5TLi4', 'Group 5 Toe in Lasso Lift Level 4'),
        ('5SLi', 'Group 5 Step in Lasso Lift'),
        ('5SLiB', 'Group 5 Step in Lasso Lift Level B'),
        ('5SLi1', 'Group 5 Step in Lasso Lift Level 1'),
        ('5SLi2', 'Group 5 Step in Lasso Lift Level 2'),
        ('5SLi3', 'Group 5 Step in Lasso Lift Level 3'),
        ('5SLi4', 'Group 5 Step in Lasso Lift Level 4'),
        ('5ALi', 'Group 5 Axel Lasso Lift'),
        ('5ALiB', 'Group 5 Axel Lasso Lift Level B'),
        ('5ALi1', 'Group 5 Axel Lasso Lift Level 1'),
        ('5ALi2', 'Group 5 Axel Lasso Lift Level 2'),
        ('5ALi3', 'Group 5 Axel Lasso Lift Level 3'),
        ('5ALi4', 'Group 5 Axel Lasso Lift Level 4'),
        ('5BLi', 'Group 5 Backward Lasso Lift'),
        ('5BLiB', 'Group 5 Backward Lasso Lift Level B'),
        ('5BLi1', 'Group 5 Backward Lasso Lift Level 1'),
        ('5BLi2', 'Group 5 Backward Lasso Lift Level 2'),
        ('5BLi3', 'Group 5 Backward Lasso Lift Level 3'),
        ('5BLi4', 'Group 5 Backward Lasso Lift Level 4'),
        ('5RLi', 'Group 5 Reverse Lasso Lift'),
        ('5RLiB', 'Group 5 Reverse Lasso Lift Level B'),
        ('5RLi1', 'Group 5 Reverse Lasso Lift Level 1'),
        ('5RLi2', 'Group 5 Reverse Lasso Lift Level 2'),
        ('5RLi3', 'Group 5 Reverse Lasso Lift Level 3'),
        ('5RLi4', 'Group 5 Reverse Lasso Lift Level 4'),
        ('5LoLi', '5LoLi'),
        ('5LoLiB', '5LoLiB'),
        ('5LoLi1', '5LoLi1'),
        ('5LoLi2', '5LoLi2'),
        ('5LoLi3', '5LoLi3'),
        ('5LoLi4', '5LoLi4'),
        ('1Tw', 'Single Twist Lift'),
        ('1TwB', 'Single Twist Lift Level B'),
        ('1Tw1', 'Single Twist Lift Level 1'),
        ('1Tw2', 'Single Twist Lift Level 2'),
        ('1Tw3', 'Single Twist Lift Level 3'),
        ('1Tw4', 'Single Twist Lift Level 4'),
        ('2Tw', 'Double Twist Lift'),
        ('2TwB', 'Double Twist Lift Level B'),
        ('2Tw1', 'Double Twist Lift Level 1'),
        ('2Tw2', 'Double Twist Lift Level 2'),
        ('2Tw3', 'Double Twist Lift Level 3'),
        ('2Tw4', 'Double Twist Lift Level 4'),
        ('3Tw', 'Triple Twist Lift'),
        ('3TwB', 'Triple Twist Lift Level B'),
        ('3Tw1', 'Triple Twist Lift Level 1'),
        ('3Tw2', 'Triple Twist Lift Level 2'),
        ('3Tw3', 'Triple Twist Lift Level 3'),
        ('3Tw4', 'Triple Twist Lift Level 4'),
        ('4Tw', 'Quadruple Twist Lift'),
        ('4TwB', 'Quadruple Twist Lift Level B'),
        ('4Tw1', 'Quadruple Twist Lift Level 1'),
        ('4Tw2', 'Quadruple Twist Lift Level 2'),
        ('4Tw3', 'Quadruple Twist Lift Level 3'),
        ('4Tw4', 'Quadruple Twist Lift Level 4'),
        ('1LzTw', 'Single Lutz Twist'),
        ('1LzTwB', 'Single Lutz Twist Level B'),
        ('1LzTw1', 'Single Lutz Twist Level 1'),
        ('1LzTw2', 'Single Lutz Twist Level 2'),
        ('1LzTw3', 'Single Lutz Twist Level 3'),
        ('1LzTw4', 'Single Lutz Twist Level 4'),
        ('2LzTw', 'Double Lutz Twist'),
        ('2LzTwB', 'Double Lutz Twist Level B'),
        ('2LzTw1', 'Double Lutz Twist Level 1'),
        ('2LzTw2', 'Double Lutz Twist Level 2'),
        ('2LzTw3', 'Double Lutz Twist Level 3'),
        ('2LzTw4', 'Double Lutz Twist Level 4'),
        ('3LzTw', 'Triple Lutz Twist'),
        ('3LzTwB', 'Triple Lutz Twist Level B'),
        ('3LzTw1', 'Triple Lutz Twist Level 1'),
        ('3LzTw2', 'Triple Lutz Twist Level 2'),
        ('3LzTw3', 'Triple Lutz Twist Level 3'),
        ('3LzTw4', 'Triple Lutz Twist Level 4'),
        ('4LzTw', 'Quad Lutz Twist'),
        ('4LzTwB', 'Quad Lutz Twist Level B'),
        ('4LzTw1', 'Quad Lutz Twist Level 1'),
        ('4LzTw2', 'Quad Lutz Twist Level 2'),
        ('4LzTw3', 'Quad Lutz Twist Level 3'),
        ('4LzTw4', 'Quad Lutz Twist Level 4'),
        ('1FTw', 'Single Flip Twist'),
        ('1FTwB', 'Single Flip Twist Level B'),
        ('1FTw1', 'Single Flip Twist Level 1'),
        ('1FTw2', 'Single Flip Twist Level 2'),
        ('1FTw3', 'Single Flip Twist Level 3'),
        ('1FTw4', 'Single Flip Twist Level 4'),
        ('2FTw', 'Double Flip Twist'),
        ('2FTwB', 'Double Flip Twist Level B'),
        ('2FTw1', 'Double Flip Twist Level 1'),
        ('2FTw2', 'Double Flip Twist Level 2'),
        ('2FTw3', 'Double Flip Twist Level 3'),
        ('2FTw4', 'Double Flip Twist Level 4'),
        ('3FTw', 'Triple Flip Twist'),
        ('3FTwB', 'Triple Flip Twist Level B'),
        ('3FTw1', 'Triple Flip Twist Level 1'),
        ('3FTw2', 'Triple Flip Twist Level 2'),
        ('3FTw3', 'Triple Flip Twist Level 3'),
        ('3FTw4', 'Triple Flip Twist Level 4'),
        ('4FTw', 'Quad Flip Twist'),
        ('4FTwB', 'Quad Flip Twist Level B'),
        ('4FTw1', 'Quad Flip Twist Level 1'),
        ('4FTw2', 'Quad Flip Twist Level 2'),
        ('4FTw3', 'Quad Flip Twist Level 3'),
        ('4FTw4', 'Quad Flip Twist Level 4'),
        ('1ATw', 'Single Axel Twist Lift'),
        ('1ATwB', 'Single Axel Twist Lift Level B'),
        ('1ATw1', 'Single Axel Twist Lift Level 1'),
        ('1ATw2', 'Single Axel Twist Lift Level 2'),
        ('1ATw3', 'Single Axel Twist Lift Level 3'),
        ('1ATw4', 'Single Axel Twist Lift Level 4'),
        ('2ATw', 'Double Axel Twist Lift'),
        ('2ATwB', 'Double Axel Twist Lift Level B'),
        ('2ATw1', 'Double Axel Twist Lift Level 1'),
        ('2ATw2', 'Double Axel Twist Lift Level 2'),
        ('2ATw3', 'Double Axel Twist Lift Level 3'),
        ('2ATw4', 'Double Axel Twist Lift Level 4'),
        ('3ATw', 'Triple Axel Twist Lift'),
        ('3ATwB', 'Triple Axel Twist Lift Level B'),
        ('3ATw1', 'Triple Axel Twist Lift Level 1'),
        ('3ATw2', 'Triple Axel Twist Lift Level 2'),
        ('3ATw3', 'Triple Axel Twist Lift Level 3'),
        ('3ATw4', 'Triple Axel Twist Lift Level 4'),
        ('4ATw', 'Quadruple Axel Twist Lift'),
        ('4ATwB', 'Quadruple Axel Twist Lift Level B'),
        ('4ATw1', 'Quadruple Axel Twist Lift Level 1'),
        ('4ATw2', 'Quadruple Axel Twist Lift Level 2'),
        ('4ATw3', 'Quadruple Axel Twist Lift Level 3'),
        ('4ATw4', 'Quadruple Axel Twist Lift Level 4'),
        ('TTh', 'Throw Toeloop'),
        ('STh', 'Throw Salchow'),
        ('LoTh', 'Throw Loop'),
        ('FTh', 'Throw Flip'),
        ('LzTh', 'Throw Lutz'),
        ('ATh', 'Throw Axel'),
        ('1TTh', 'Throw Single Toeloop'),
        ('1STh', 'Throw Single Salchow'),
        ('1LoTh', 'Throw Single Loop'),
        ('1FTh', 'Throw Single Flip'),
        ('1LzTh', 'Throw Single Lutz'),
        ('1ATh', 'Throw Single Axel'),
        ('2TTh', 'Throw Double Toeloop'),
        ('2STh', 'Throw Double Salchow'),
        ('2LoTh', 'Throw Double Loop'),
        ('2FTh', 'Throw Double Flip'),
        ('2LzTh', 'Throw Double Lutz'),
        ('2ATh', 'Throw Double Axel'),
        ('3TTh', 'Throw Triple Toeloop'),
        ('3STh', 'Throw Triple Salchow'),
        ('3LoTh', 'Throw Triple Loop'),
        ('3FTh', 'Throw Triple Flip'),
        ('3LzTh', 'Throw Triple Lutz'),
        ('3ATh', 'Throw Triple Axel'),
        ('4TTh', 'Throw Quadruple Toeloop'),
        ('4STh', 'Throw Quadruple Salchow'),
        ('4LoTh', 'Throw Quadruple Loop'),
        ('4FTh', 'Throw Quadruple Flip'),
        ('4LzTh', 'Throw Quadruple Lutz'),
        ('FiDs', 'Forward Inside Death Spiral'),
        ('FiDsB', 'Forward Inside Death Spiral Level B'),
        ('FiDs1', 'Forward Inside Death Spiral Level 1'),
        ('FiDs2', 'Forward Inside Death Spiral Level 2'),
        ('FiDs3', 'Forward Inside Death Spiral Level 3'),
        ('FiDs4', 'Forward Inside Death Spiral Level 4'),
        ('BiDs', 'Backward Inside Death Spiral'),
        ('BiDsB', 'Backward Inside Death Spiral Level B'),
        ('BiDs1', 'Backward Inside Death Spiral Level 1'),
        ('BiDs2', 'Backward Inside Death Spiral Level 2'),
        ('BiDs3', 'Backward Inside Death Spiral Level 3'),
        ('BiDs4', 'Backward Inside Death Spiral Level 4'),
        ('FoDs', 'Forward Outside Death Spiral'),
        ('FoDsB', 'Forward Outside Death Spiral Level B'),
        ('FoDs1', 'Forward Outside Death Spiral Level 1'),
        ('FoDs2', 'Forward Outside Death Spiral Level 2'),
        ('FoDs3', 'Forward Outside Death Spiral Level 3'),
        ('FoDs4', 'Forward Outside Death Spiral Level 4'),
        ('BoDs', 'Backward Outside Death Spiral'),
        ('BoDsB', 'Backward Outside Death Spiral Level B'),
        ('BoDs1', 'Backward Outside Death Spiral Level 1'),
        ('BoDs2', 'Backward Outside Death Spiral Level 2'),
        ('BoDs3', 'Backward Outside Death Spiral Level 3'),
        ('BoDs4', 'Backward Outside Death Spiral Level 4'),
        ('PiF', 'Pivot Figure'),
        ('PiF1', 'Pivot Figure'),
        ('PiF2', 'Pivot Figure'),
        ('PiF3', 'Pivot Figure'),
        ('PiF4', 'Pivot Figure'),
        ('PSp', 'Pair Spin'),
        ('PSpB', 'Pair Spin Level B'),
        ('PSp1', 'Pair Spin Level 1'),
        ('PSp2', 'Pair Spin Level 2'),
        ('PSp3', 'Pair Spin Level 3'),
        ('PSp4', 'Pair Spin Level 4'),
        ('PCoSp', 'Pair Combination Spin'),
        ('PCoSpB', 'Pair Combination Spin Level B'),
        ('PCoSp1', 'Pair Combination Spin Level 1'),
        ('PCoSp2', 'Pair Combination Spin Level 2'),
        ('PCoSp3', 'Pair Combination Spin Level 3'),
        ('PCoSp4', 'Pair Combination Spin Level 4'),
        ('FO1Sq', 'Fourteenstep Sequence 1'),
        ('FO1Sq1', 'Fourteenstep Sequence 1 Level 1'),
        ('FO1Sq2', 'Fourteenstep Sequence 1 Level 2'),
        ('FO1Sq3', 'Fourteenstep Sequence 1 Level 3'),
        ('FO1Sq4', 'Fourteenstep Sequence 1 Level 4'),
        ('FO2Sq', 'Fourteenstep Sequence 2'),
        ('FO2Sq1', 'Fourteenstep Sequence 2 Level 1'),
        ('FO2Sq2', 'Fourteenstep Sequence 2 Level 2'),
        ('FO2Sq3', 'Fourteenstep Sequence 2 Level 3'),
        ('FO2Sq4', 'Fourteenstep Sequence 2 Level 4'),
        ('FO3Sq', 'Fourteenstep Sequence 3'),
        ('FO3Sq1', 'Fourteenstep Sequence 3 Level 1'),
        ('FO3Sq2', 'Fourteenstep Sequence 3 Level 2'),
        ('FO3Sq3', 'Fourteenstep Sequence 3 Level 3'),
        ('FO3Sq4', 'Fourteenstep Sequence 3 Level 4'),
        ('FO4Sq', 'Fourteenstep Sequence 4'),
        ('FO4Sq1', 'Fourteenstep Sequence 4 Level 1'),
        ('FO4Sq2', 'Fourteenstep Sequence 4 Level 2'),
        ('FO4Sq3', 'Fourteenstep Sequence 4 Level 3'),
        ('FO4Sq4', 'Fourteenstep Sequence 4 Level 4'),
        ('FT1Sq', 'Foxtrot Sequence 1'),
        ('FT1Sq1', 'Foxtrot Sequence 1 Level 1'),
        ('FT1Sq2', 'Foxtrot Sequence 1 Level 2'),
        ('FT1Sq3', 'Foxtrot Sequence 1 Level 3'),
        ('FT1Sq4', 'Foxtrot Sequence 1 Level 4'),
        ('FT2Sq', 'Foxtrot Sequence 2'),
        ('FT2Sq1', 'Foxtrot Sequence 2 Level 1'),
        ('FT2Sq2', 'Foxtrot Sequence 2 Level 2'),
        ('FT2Sq3', 'Foxtrot Sequence 2 Level 3'),
        ('FT2Sq4', 'Foxtrot Sequence 2 Level 4'),
        ('FT3Sq', 'Foxtrot Sequence 3'),
        ('FT3Sq1', 'Foxtrot Sequence 3 Level 1'),
        ('FT3Sq2', 'Foxtrot Sequence 3 Level 2'),
        ('FT3Sq3', 'Foxtrot Sequence 3 Level 3'),
        ('FT3Sq4', 'Foxtrot Sequence 3 Level 4'),
        ('FT4Sq', 'Foxtrot Sequence 4'),
        ('FT4Sq1', 'Foxtrot Sequence 4 Level 1'),
        ('FT4Sq2', 'Foxtrot Sequence 4 Level 2'),
        ('FT4Sq3', 'Foxtrot Sequence 4 Level 3'),
        ('FT4Sq4', 'Foxtrot Sequence 4 Level 4'),
        ('RFT1Sq', 'Rocker Foxtrot Sequence 1'),
        ('RFT1Sq1', 'Rocker Foxtrot Sequence 1 Level 1'),
        ('RFT1Sq2', 'Rocker Foxtrot Sequence 1 Level 2'),
        ('RFT1Sq3', 'Rocker Foxtrot Sequence 1 Level 3'),
        ('RFT1Sq4', 'Rocker Foxtrot Sequence 1 Level 4'),
        ('RFT2Sq', 'Rocker Foxtrot Sequence 2'),
        ('RFT2Sq1', 'Rocker Foxtrot Sequence 2 Level 1'),
        ('RFT2Sq2', 'Rocker Foxtrot Sequence 2 Level 2'),
        ('RFT2Sq3', 'Rocker Foxtrot Sequence 2 Level 3'),
        ('RFT2Sq4', 'Rocker Foxtrot Sequence 2 Level 4'),
        ('RFT3Sq', 'Rocker Foxtrot Sequence 3'),
        ('RFT3Sq1', 'Rocker Foxtrot Sequence 3 Level 1'),
        ('RFT3Sq2', 'Rocker Foxtrot Sequence 3 Level 2'),
        ('RFT3Sq3', 'Rocker Foxtrot Sequence 3 Level 3'),
        ('RFT3Sq4', 'Rocker Foxtrot Sequence 3 Level 4'),
        ('RFT4Sq', 'Rocker Foxtrot Sequence 4'),
        ('RFT4Sq1', 'Rocker Foxtrot Sequence 4 Level 1'),
        ('RFT4Sq2', 'Rocker Foxtrot Sequence 4 Level 2'),
        ('RFT4Sq3', 'Rocker Foxtrot Sequence 4 Level 3'),
        ('RFT4Sq4', 'Rocker Foxtrot Sequence 4 Level 4'),
        ('EW1Sq', 'European Waltz Sequence 1'),
        ('EW1Sq1', 'European Waltz Sequence 1 Level 1'),
        ('EW1Sq2', 'European Waltz Sequence 1 Level 2'),
        ('EW1Sq3', 'European Waltz Sequence 1 Level 3'),
        ('EW1Sq4', 'European Waltz Sequence 1 Level 4'),
        ('EW2Sq', 'European Waltz Sequence 2'),
        ('EW2Sq1', 'European Waltz Sequence 2 Level 1'),
        ('EW2Sq2', 'European Waltz Sequence 2 Level 2'),
        ('EW2Sq3', 'European Waltz Sequence 2 Level 3'),
        ('EW2Sq4', 'European Waltz Sequence 2 Level 4'),
        ('AW1Sq', 'American Waltz Sequence 1'),
        ('AW1Sq1', 'American Waltz Sequence 1 Level 1'),
        ('AW1Sq2', 'American Waltz Sequence 1 Level 2'),
        ('AW1Sq3', 'American Waltz Sequence 1 Level 3'),
        ('AW1Sq4', 'American Waltz Sequence 1 Level 4'),
        ('AW2Sq', 'American Waltz Sequence 2'),
        ('AW2Sq1', 'American Waltz Sequence 2 Level 1'),
        ('AW2Sq2', 'American Waltz Sequence 2 Level 2'),
        ('AW2Sq3', 'American Waltz Sequence 2 Level 3'),
        ('AW2Sq4', 'American Waltz Sequence 2 Level 4'),
        ('WW1Sq1Se', 'Westminster Waltz Sequence 1 Section 1'),
        ('WW1Sq1Se1', 'Westminster Waltz Sequence 1 Section 1 Level 1'),
        ('WW1Sq1Se2', 'Westminster Waltz Sequence 1 Section 1 Level 2'),
        ('WW1Sq1Se3', 'Westminster Waltz Sequence 1 Section 1 Level 3'),
        ('WW1Sq1Se4', 'Westminster Waltz Sequence 1 Section 1 Level 4'),
        ('WW1Sq2Se', 'Westminster Waltz Sequence 1 Section 2'),
        ('WW1Sq2Se1', 'Westminster Waltz Sequence 1 Section 2 Level 1'),
        ('WW1Sq2Se2', 'Westminster Waltz Sequence 1 Section 2 Level 2'),
        ('WW1Sq2Se3', 'Westminster Waltz Sequence 1 Section 2 Level 3'),
        ('WW1Sq2Se4', 'Westminster Waltz Sequence 1 Section 2 Level 4'),
        ('WW2Sq1Se', 'Westminster Waltz Sequence 2 Section 1'),
        ('WW2Sq1Se1', 'Westminster Waltz Sequence 2 Section 1 Level 1'),
        ('WW2Sq1Se2', 'Westminster Waltz Sequence 2 Section 1 Level 2'),
        ('WW2Sq1Se3', 'Westminster Waltz Sequence 2 Section 1 Level 3'),
        ('WW2Sq1Se4', 'Westminster Waltz Sequence 2 Section 1 Level 4'),
        ('WW2Sq2Se', 'Westminster Waltz Sequence 2 Section 2'),
        ('WW2Sq2Se1', 'Westminster Waltz Sequence 2 Section 2 Level 1'),
        ('WW2Sq2Se2', 'Westminster Waltz Sequence 2 Section 2 Level 2'),
        ('WW2Sq2Se3', 'Westminster Waltz Sequence 2 Section 2 Level 3'),
        ('WW2Sq2Se4', 'Westminster Waltz Sequence 2 Section 2 Level 4'),
        ('VW1Sq', 'Viennese Waltz Sequence 1'),
        ('VW1Sq1', 'Viennese Waltz Sequence 1 Level 1'),
        ('VW1Sq2', 'Viennese Waltz Sequence 1 Level 2'),
        ('VW1Sq3', 'Viennese Waltz Sequence 1 Level 3'),
        ('VW1Sq4', 'Viennese Waltz Sequence 1 Level 4'),
        ('VW2Sq', 'Viennese Waltz Sequence 2'),
        ('VW2Sq1', 'Viennese Waltz Sequence 2 Level 1'),
        ('VW2Sq2', 'Viennese Waltz Sequence 2 Level 2'),
        ('VW2Sq3', 'Viennese Waltz Sequence 2 Level 3'),
        ('VW2Sq4', 'Viennese Waltz Sequence 2 Level 4'),
        ('VW3Sq', 'Viennese Waltz Sequence 3'),
        ('VW3Sq1', 'Viennese Waltz Sequence 3 Level 1'),
        ('VW3Sq2', 'Viennese Waltz Sequence 3 Level 2'),
        ('VW3Sq3', 'Viennese Waltz Sequence 3 Level 3'),
        ('VW3Sq4', 'Viennese Waltz Sequence 3 Level 4'),
        ('OW1Sq1Se', 'Austrian Waltz Sequence 1 Section 1'),
        ('OW1Sq1Se1', 'Austrian Waltz Sequence 1 Section 1 Level 1'),
        ('OW1Sq1Se2', 'Austrian Waltz Sequence 1 Section 1 Level 2'),
        ('OW1Sq1Se3', 'Austrian Waltz Sequence 1 Section 1 Level 3'),
        ('OW1Sq1Se4', 'Austrian Waltz Sequence 1 Section 1 Level 4'),
        ('OW1Sq2Se', 'Austrian Waltz Sequence 1 Section 2'),
        ('OW1Sq2Se1', 'Austrian Waltz Sequence 1 Section 2 Level 1'),
        ('OW1Sq2Se2', 'Austrian Waltz Sequence 1 Section 2 Level 2'),
        ('OW1Sq2Se3', 'Austrian Waltz Sequence 1 Section 2 Level 3'),
        ('OW1Sq2Se4', 'Austrian Waltz Sequence 1 Section 2 Level 4'),
        ('OW2Sq1Se', 'Austrian Waltz Sequence 2 Section 1'),
        ('OW2Sq1Se1', 'Austrian Waltz Sequence 2 Section 1 Level 1'),
        ('OW2Sq1Se2', 'Austrian Waltz Sequence 2 Section 1 Level 2'),
        ('OW2Sq1Se3', 'Austrian Waltz Sequence 2 Section 1 Level 3'),
        ('OW2Sq1Se4', 'Austrian Waltz Sequence 2 Section 1 Level 4'),
        ('OW2Sq2Se', 'Austrian Waltz Sequence 2 Section 2'),
        ('OW2Sq2Se1', 'Austrian Waltz Sequence 2 Section 2 Level 1'),
        ('OW2Sq2Se2', 'Austrian Waltz Sequence 2 Section 2 Level 2'),
        ('OW2Sq2Se3', 'Austrian Waltz Sequence 2 Section 2 Level 3'),
        ('OW2Sq2Se4', 'Austrian Waltz Sequence 2 Section 2 Level 4'),
        ('SW1Sq1Se', 'Starlight Waltz Sequence 1 Section 1'),
        ('SW1Sq1Se1', 'Starlight Waltz Sequence 1 Section 1 Level 1'),
        ('SW1Sq1Se2', 'Starlight Waltz Sequence 1 Section 1 Level 2'),
        ('SW1Sq1Se3', 'Starlight Waltz Sequence 1 Section 1 Level 3'),
        ('SW1Sq1Se4', 'Starlight Waltz Sequence 1 Section 1 Level 4'),
        ('SW1Sq2Se', 'Starlight Waltz Sequence 1 Section 2'),
        ('SW1Sq2Se1', 'Starlight Waltz Sequence 1 Section 2 Level 1'),
        ('SW1Sq2Se2', 'Starlight Waltz Sequence 1 Section 2 Level 2'),
        ('SW1Sq2Se3', 'Starlight Waltz Sequence 1 Section 2 Level 3'),
        ('SW1Sq2Se4', 'Starlight Waltz Sequence 1 Section 2 Level 4'),
        ('SW2Sq1Se', 'Starlight Waltz Sequence 2 Section 1'),
        ('SW2Sq1Se1', 'Starlight Waltz Sequence 2 Section 1 Level 1'),
        ('SW2Sq1Se2', 'Starlight Waltz Sequence 2 Section 1 Level 2'),
        ('SW2Sq1Se3', 'Starlight Waltz Sequence 2 Section 1 Level 3'),
        ('SW2Sq1Se4', 'Starlight Waltz Sequence 2 Section 1 Level 4'),
        ('SW2Sq2Se', 'Starlight Waltz Sequence 2 Section 2'),
        ('SW2Sq2Se1', 'Starlight Waltz Sequence 2 Section 2 Level 1'),
        ('SW2Sq2Se2', 'Starlight Waltz Sequence 2 Section 2 Level 2'),
        ('SW2Sq2Se3', 'Starlight Waltz Sequence 2 Section 2 Level 3'),
        ('SW2Sq2Se4', 'Starlight Waltz Sequence 2 Section 2 Level 4'),
        ('RW1Sq1Se', 'Ravensburger Waltz Sequence 1 Section 1'),
        ('RW1Sq1Se1', 'Ravensburger Waltz Sequence 1 Section 1 Level 1'),
        ('RW1Sq1Se2', 'Ravensburger Waltz Sequence 1 Section 1 Level 2'),
        ('RW1Sq1Se3', 'Ravensburger Waltz Sequence 1 Section 1 Level 3'),
        ('RW1Sq1Se4', 'Ravensburger Waltz Sequence 1 Section 1 Level 4'),
        ('RW1Sq2Se', 'Ravensburger Waltz Sequence 1 Section 2'),
        ('RW1Sq2Se1', 'Ravensburger Waltz Sequence 1 Section 2 Level 1'),
        ('RW1Sq2Se2', 'Ravensburger Waltz Sequence 1 Section 2 Level 2'),
        ('RW1Sq2Se3', 'Ravensburger Waltz Sequence 1 Section 2 Level 3'),
        ('RW1Sq2Se4', 'Ravensburger Waltz Sequence 1 Section 2 Level 4'),
        ('RW2Sq1Se', 'Ravensburger Waltz Sequence 2 Section 1'),
        ('RW2Sq1Se1', 'Ravensburger Waltz Sequence 2 Section 1 Level 1'),
        ('RW2Sq1Se2', 'Ravensburger Waltz Sequence 2 Section 1 Level 2'),
        ('RW2Sq1Se3', 'Ravensburger Waltz Sequence 2 Section 1 Level 3'),
        ('RW2Sq1Se4', 'Ravensburger Waltz Sequence 2 Section 1 Level 4'),
        ('RW2Sq2Se', 'Ravensburger Waltz Sequence 2 Section 2'),
        ('RW2Sq2Se1', 'Ravensburger Waltz Sequence 2 Section 2 Level 1'),
        ('RW2Sq2Se2', 'Ravensburger Waltz Sequence 2 Section 2 Level 2'),
        ('RW2Sq2Se3', 'Ravensburger Waltz Sequence 2 Section 2 Level 3'),
        ('RW2Sq2Se4', 'Ravensburger Waltz Sequence 2 Section 2 Level 4'),
        ('GW1Sq1Se', 'Golden Waltz Sequence 1 Section 1'),
        ('GW1Sq1Se1', 'Golden Waltz Sequence 1 Section 1 Level 1'),
        ('GW1Sq1Se2', 'Golden Waltz Sequence 1 Section 1 Level 2'),
        ('GW1Sq1Se3', 'Golden Waltz Sequence 1 Section 1 Level 3'),
        ('GW1Sq1Se4', 'Golden Waltz Sequence 1 Section 1 Level 4'),
        ('GW1Sq2Se', 'Golden Waltz Sequence 1 Section 2'),
        ('GW1Sq2Se1', 'Golden Waltz Sequence 1 Section 2 Level 1'),
        ('GW1Sq2Se2', 'Golden Waltz Sequence 1 Section 2 Level 2'),
        ('GW1Sq2Se3', 'Golden Waltz Sequence 1 Section 2 Level 3'),
        ('GW1Sq2Se4', 'Golden Waltz Sequence 1 Section 2 Level 4'),
        ('GW2Sq1Se', 'Golden Waltz Sequence 2 Section 1'),
        ('GW2Sq1Se1', 'Golden Waltz Sequence 2 Section 1 Level 1'),
        ('GW2Sq1Se2', 'Golden Waltz Sequence 2 Section 1 Level 2'),
        ('GW2Sq1Se3', 'Golden Waltz Sequence 2 Section 1 Level 3'),
        ('GW2Sq1Se4', 'Golden Waltz Sequence 2 Section 1 Level 4'),
        ('GW2Sq2Se', 'Golden Waltz Sequence 2 Section 2'),
        ('GW2Sq2Se1', 'Golden Waltz Sequence 2 Section 2 Level 1'),
        ('GW2Sq2Se2', 'Golden Waltz Sequence 2 Section 2 Level 2'),
        ('GW2Sq2Se3', 'Golden Waltz Sequence 2 Section 2 Level 3'),
        ('GW2Sq2Se4', 'Golden Waltz Sequence 2 Section 2 Level 4'),
        ('KI1Sq', 'Kilian Sequence 1'),
        ('KI1Sq1', 'Kilian Sequence 1 Level 1'),
        ('KI1Sq2', 'Kilian Sequence 1 Level 2'),
        ('KI1Sq3', 'Kilian Sequence 1 Level 3'),
        ('KI1Sq4', 'Kilian Sequence 1 Level 4'),
        ('KI2Sq', 'Kilian Sequence 2'),
        ('KI2Sq1', 'Kilian Sequence 2 Level 1'),
        ('KI2Sq2', 'Kilian Sequence 2 Level 2'),
        ('KI2Sq3', 'Kilian Sequence 2 Level 3'),
        ('KI2Sq4', 'Kilian Sequence 2 Level 4'),
        ('KI3Sq', 'Kilian Sequence 3'),
        ('KI3Sq1', 'Kilian Sequence 3 Level 1'),
        ('KI3Sq2', 'Kilian Sequence 3 Level 2'),
        ('KI3Sq3', 'Kilian Sequence 3 Level 3'),
        ('KI3Sq4', 'Kilian Sequence 3 Level 4'),
        ('KI4Sq', 'Kilian Sequence 4'),
        ('KI4Sq1', 'Kilian Sequence 4 Level 1'),
        ('KI4Sq2', 'Kilian Sequence 4 Level 2'),
        ('KI4Sq3', 'Kilian Sequence 4 Level 3'),
        ('KI4Sq4', 'Kilian Sequence 4 Level 4'),
        ('KI5Sq', 'Kilian Sequence 5'),
        ('KI5Sq1', 'Kilian Sequence 5 Level 1'),
        ('KI5Sq2', 'Kilian Sequence 5 Level 2'),
        ('KI5Sq3', 'Kilian Sequence 5 Level 3'),
        ('KI5Sq4', 'Kilian Sequence 5 Level 4'),
        ('KI6Sq', 'Kilian Sequence 6'),
        ('KI6Sq1', 'Kilian Sequence 6 Level 1'),
        ('KI6Sq2', 'Kilian Sequence 6 Level 2'),
        ('KI6Sq3', 'Kilian Sequence 6 Level 3'),
        ('KI6Sq4', 'Kilian Sequence 6 Level 4'),
        ('YP1Sq1Se', 'Yankee Polka Sequence 1 Section 1'),
        ('YP1Sq1Se1', 'Yankee Polka Sequence 1 Section 1 Level 1'),
        ('YP1Sq1Se2', 'Yankee Polka Sequence 1 Section 1 Level 2'),
        ('YP1Sq1Se3', 'Yankee Polka Sequence 1 Section 1 Level 3'),
        ('YP1Sq1Se4', 'Yankee Polka Sequence 1 Section 1 Level 4'),
        ('YP1Sq2Se', 'Yankee Polka Sequence 1 Section 2'),
        ('YP1Sq2Se1', 'Yankee Polka Sequence 1 Section 2 Level 1'),
        ('YP1Sq2Se2', 'Yankee Polka Sequence 1 Section 2 Level 2'),
        ('YP1Sq2Se3', 'Yankee Polka Sequence 1 Section 2 Level 3'),
        ('YP1Sq2Se4', 'Yankee Polka Sequence 1 Section 2 Level 4'),
        ('YP2Sq1Se', 'Yankee Polka Sequence 2 Section 1'),
        ('YP2Sq1Se1', 'Yankee Polka Sequence 2 Section 1 Level 1'),
        ('YP2Sq1Se2', 'Yankee Polka Sequence 2 Section 1 Level 2'),
        ('YP2Sq1Se3', 'Yankee Polka Sequence 2 Section 1 Level 3'),
        ('YP2Sq1Se4', 'Yankee Polka Sequence 2 Section 1 Level 4'),
        ('YP2Sq2Se', 'Yankee Polka Sequence 2 Section 2'),
        ('YP2Sq2Se1', 'Yankee Polka Sequence 2 Section 2 Level 1'),
        ('YP2Sq2Se2', 'Yankee Polka Sequence 2 Section 2 Level 2'),
        ('YP2Sq2Se3', 'Yankee Polka Sequence 2 Section 2 Level 3'),
        ('YP2Sq2Se4', 'Yankee Polka Sequence 2 Section 2 Level 4'),
        ('QS1Sq', 'Quikstep Sequence 1'),
        ('QS1Sq1', 'Quikstep Sequence 1 Level 1'),
        ('QS1Sq2', 'Quikstep Sequence 1 Level 2'),
        ('QS1Sq3', 'Quikstep Sequence 1 Level 3'),
        ('QS1Sq4', 'Quikstep Sequence 1 Level 4'),
        ('QS2Sq', 'Quikstep Sequence 2'),
        ('QS2Sq1', 'Quikstep Sequence 2 Level 1'),
        ('QS2Sq2', 'Quikstep Sequence 2 Level 2'),
        ('QS2Sq3', 'Quikstep Sequence 2 Level 3'),
        ('QS2Sq4', 'Quikstep Sequence 2 Level 4'),
        ('QS3Sq', 'Quikstep Sequence 3'),
        ('QS3Sq1', 'Quikstep Sequence 3 Level 1'),
        ('QS3Sq2', 'Quikstep Sequence 3 Level 2'),
        ('QS3Sq3', 'Quikstep Sequence 3 Level 3'),
        ('QS3Sq4', 'Quikstep Sequence 3 Level 4'),
        ('QS4Sq', 'Quikstep Sequence 4'),
        ('QS4Sq1', 'Quikstep Sequence 4 Level 1'),
        ('QS4Sq2', 'Quikstep Sequence 4 Level 2'),
        ('QS4Sq3', 'Quikstep Sequence 4 Level 3'),
        ('QS4Sq4', 'Quikstep Sequence 4 Level 4'),
        ('FS1Sq1Se', 'Finnstep Sequence 1 Section 1'),
        ('FS1Sq1Se1', 'Finnstep Sequence 1 Section 1 Level 1'),
        ('FS1Sq1Se2', 'Finnstep Sequence 1 Section 1 Level 2'),
        ('FS1Sq1Se3', 'Finnstep Sequence 1 Section 1 Level 3'),
        ('FS1Sq1Se4', 'Finnstep Sequence 1 Section 1 Level 4'),
        ('FS1Sq2Se', 'Finnstep Sequence 1 Section 2'),
        ('FS1Sq2Se1', 'Finnstep Sequence 1 Section 2 Level 1'),
        ('FS1Sq2Se2', 'Finnstep Sequence 1 Section 2 Level 2'),
        ('FS1Sq2Se3', 'Finnstep Sequence 1 Section 2 Level 3'),
        ('FS1Sq2Se4', 'Finnstep Sequence 1 Section 2 Level 4'),
        ('FS2Sq1Se', 'Finnstep Sequence 2 Section 1'),
        ('FS2Sq1Se1', 'Finnstep Sequence 2 Section 1 Level 1'),
        ('FS2Sq1Se2', 'Finnstep Sequence 2 Section 1 Level 2'),
        ('FS2Sq1Se3', 'Finnstep Sequence 2 Section 1 Level 3'),
        ('FS2Sq1Se4', 'Finnstep Sequence 2 Section 1 Level 4'),
        ('FS2Sq2Se', 'Finnstep Sequence 2 Section 2'),
        ('FS2Sq2Se1', 'Finnstep Sequence 2 Section 2 Level 1'),
        ('FS2Sq2Se2', 'Finnstep Sequence 2 Section 2 Level 2'),
        ('FS2Sq2Se3', 'Finnstep Sequence 2 Section 2 Level 3'),
        ('FS2Sq2Se4', 'Finnstep Sequence 2 Section 2 Level 4'),
        ('PD1Sq', 'Paso Doble Sequence 1'),
        ('PD1Sq1', 'Paso Doble Sequence 1 Level 1'),
        ('PD1Sq2', 'Paso Doble Sequence 1 Level 2'),
        ('PD1Sq3', 'Paso Doble Sequence 1 Level 3'),
        ('PD1Sq4', 'Paso Doble Sequence 1 Level 4'),
        ('PD2Sq', 'Paso Doble Sequence 2'),
        ('PD2Sq1', 'Paso Doble Sequence 2 Level 1'),
        ('PD2Sq2', 'Paso Doble Sequence 2 Level 2'),
        ('PD2Sq3', 'Paso Doble Sequence 2 Level 3'),
        ('PD2Sq4', 'Paso Doble Sequence 2 Level 4'),
        ('PD3Sq', 'Paso Doble Sequence 3'),
        ('PD3Sq1', 'Paso Doble Sequence 3 Level 1'),
        ('PD3Sq2', 'Paso Doble Sequence 3 Level 2'),
        ('PD3Sq3', 'Paso Doble Sequence 3 Level 3'),
        ('PD3Sq4', 'Paso Doble Sequence 3 Level 4'),
        ('RH1Sq', 'Rhumba Sequence 1'),
        ('RH1Sq1', 'Rhumba Sequence 1 Level 1'),
        ('RH1Sq2', 'Rhumba Sequence 1 Level 2'),
        ('RH1Sq3', 'Rhumba Sequence 1 Level 3'),
        ('RH1Sq4', 'Rhumba Sequence 1 Level 4'),
        ('RH2Sq', 'Rhumba Sequence 2'),
        ('RH2Sq1', 'Rhumba Sequence 2 Level 1'),
        ('RH2Sq2', 'Rhumba Sequence 2 Level 2'),
        ('RH2Sq3', 'Rhumba Sequence 2 Level 3'),
        ('RH2Sq4', 'Rhumba Sequence 2 Level 4'),
        ('RH3Sq', 'Rhumba Sequence 3'),
        ('RH3Sq1', 'Rhumba Sequence 3 Level 1'),
        ('RH3Sq2', 'Rhumba Sequence 3 Level 2'),
        ('RH3Sq3', 'Rhumba Sequence 3 Level 3'),
        ('RH3Sq4', 'Rhumba Sequence 3 Level 4'),
        ('RH4Sq', 'Rhumba Sequence 4'),
        ('RH4Sq1', 'Rhumba Sequence 4 Level 1'),
        ('RH4Sq2', 'Rhumba Sequence 4 Level 2'),
        ('RH4Sq3', 'Rhumba Sequence 4 Level 3'),
        ('RH4Sq4', 'Rhumba Sequence 4 Level 4'),
        ('CC1Sq', 'Cha Cha Congelado Sequence 1'),
        ('CC1Sq1', 'Cha Cha Congelado Sequence 1 Level 1'),
        ('CC1Sq2', 'Cha Cha Congelado Sequence 1 Level 2'),
        ('CC1Sq3', 'Cha Cha Congelado Sequence 1 Level 3'),
        ('CC1Sq4', 'Cha Cha Congelado Sequence 1 Level 4'),
        ('CC2Sq', 'Cha Cha Congelado Sequence 2'),
        ('CC2Sq1', 'Cha Cha Congelado Sequence 2 Level 1'),
        ('CC2Sq2', 'Cha Cha Congelado Sequence 2 Level 2'),
        ('CC2Sq3', 'Cha Cha Congelado Sequence 2 Level 3'),
        ('CC2Sq4', 'Cha Cha Congelado Sequence 2 Level 4'),
        ('SS1Sq1Se', 'Silver Samba Sequence 1 Section 1'),
        ('SS1Sq1Se1', 'Silver Samba Sequence 1 Section 1 Level 1'),
        ('SS1Sq1Se2', 'Silver Samba Sequence 1 Section 1 Level 2'),
        ('SS1Sq1Se3', 'Silver Samba Sequence 1 Section 1 Level 3'),
        ('SS1Sq1Se4', 'Silver Samba Sequence 1 Section 1 Level 4'),
        ('SS1Sq2Se', 'Silver Samba Sequence 1 Section 2'),
        ('SS1Sq2Se1', 'Silver Samba Sequence 1 Section 2 Level 1'),
        ('SS1Sq2Se2', 'Silver Samba Sequence 1 Section 2 Level 2'),
        ('SS1Sq2Se3', 'Silver Samba Sequence 1 Section 2 Level 3'),
        ('SS1Sq2Se4', 'Silver Samba Sequence 1 Section 2 Level 4'),
        ('SS2Sq1Se', 'Silver Samba Sequence 2 Section 1'),
        ('SS2Sq1Se1', 'Silver Samba Sequence 2 Section 1 Level 1'),
        ('SS2Sq1Se2', 'Silver Samba Sequence 2 Section 1 Level 2'),
        ('SS2Sq1Se3', 'Silver Samba Sequence 2 Section 1 Level 3'),
        ('SS2Sq1Se4', 'Silver Samba Sequence 2 Section 1 Level 4'),
        ('SS2Sq2Se', 'Silver Samba Sequence 2 Section 2'),
        ('SS2Sq2Se1', 'Silver Samba Sequence 2 Section 2 Level 1'),
        ('SS2Sq2Se2', 'Silver Samba Sequence 2 Section 2 Level 2'),
        ('SS2Sq2Se3', 'Silver Samba Sequence 2 Section 2 Level 3'),
        ('SS2Sq2Se4', 'Silver Samba Sequence 2 Section 2 Level 4'),
        ('TA1Sq', 'Tango Sequence 1'),
        ('TA1Sq1', 'Tango Sequence 1 Level 1'),
        ('TA1Sq2', 'Tango Sequence 1 Level 2'),
        ('TA1Sq3', 'Tango Sequence 1 Level 3'),
        ('TA1Sq4', 'Tango Sequence 1 Level 4'),
        ('TA2Sq', 'Tango Sequence 2'),
        ('TA2Sq1', 'Tango Sequence 2 Level 1'),
        ('TA2Sq2', 'Tango Sequence 2 Level 2'),
        ('TA2Sq3', 'Tango Sequence 2 Level 3'),
        ('TA2Sq4', 'Tango Sequence 2 Level 4'),
        ('AT1Sq1Se', 'Argentine Tango Sequence 1 Section 1'),
        ('AT1Sq1Se1', 'Argentine Tango Sequence 1 Section 1 Level 1'),
        ('AT1Sq1Se2', 'Argentine Tango Sequence 1 Section 1 Level 2'),
        ('AT1Sq1Se3', 'Argentine Tango Sequence 1 Section 1 Level 3'),
        ('AT1Sq1Se4', 'Argentine Tango Sequence 1 Section 1 Level 4'),
        ('AT1Sq2Se', 'Argentine Tango Sequence 1 Section 2'),
        ('AT1Sq2Se1', 'Argentine Tango Sequence 1 Section 2 Level 1'),
        ('AT1Sq2Se2', 'Argentine Tango Sequence 1 Section 2 Level 2'),
        ('AT1Sq2Se3', 'Argentine Tango Sequence 1 Section 2 Level 3'),
        ('AT1Sq2Se4', 'Argentine Tango Sequence 1 Section 2 Level 4'),
        ('AT2Sq1Se', 'Argentine Tango Sequence 2 Section 1'),
        ('AT2Sq1Se1', 'Argentine Tango Sequence 2 Section 1 Level 1'),
        ('AT2Sq1Se2', 'Argentine Tango Sequence 2 Section 1 Level 2'),
        ('AT2Sq1Se3', 'Argentine Tango Sequence 2 Section 1 Level 3'),
        ('AT2Sq1Se4', 'Argentine Tango Sequence 2 Section 1 Level 4'),
        ('AT2Sq2Se', 'Argentine Tango Sequence 2 Section 2'),
        ('AT2Sq2Se1', 'Argentine Tango Sequence 2 Section 2 Level 1'),
        ('AT2Sq2Se2', 'Argentine Tango Sequence 2 Section 2 Level 2'),
        ('AT2Sq2Se3', 'Argentine Tango Sequence 2 Section 2 Level 3'),
        ('AT2Sq2Se4', 'Argentine Tango Sequence 2 Section 2 Level 4'),
        ('TR1Sq1Se', 'Tango Romantica Sequence 1 Section 1'),
        ('TR1Sq1Se1', 'Tango Romantica Sequence 1 Section 1 Level 1'),
        ('TR1Sq1Se2', 'Tango Romantica Sequence 1 Section 1 Level 2'),
        ('TR1Sq1Se3', 'Tango Romantica Sequence 1 Section 1 Level 3'),
        ('TR1Sq1Se4', 'Tango Romantica Sequence 1 Section 1 Level 4'),
        ('TR1Sq2Se', 'Tango Romantica Sequence 1 Section 2'),
        ('TR1Sq2Se1', 'Tango Romantica Sequence 1 Section 2 Level 1'),
        ('TR1Sq2Se2', 'Tango Romantica Sequence 1 Section 2 Level 2'),
        ('TR1Sq2Se3', 'Tango Romantica Sequence 1 Section 2 Level 3'),
        ('TR1Sq2Se4', 'Tango Romantica Sequence 1 Section 2 Level 4'),
        ('TR2Sq1Se', 'Tango Romantica Sequence 2 Section 1'),
        ('TR2Sq1Se1', 'Tango Romantica Sequence 2 Section 1 Level 1'),
        ('TR2Sq1Se2', 'Tango Romantica Sequence 2 Section 1 Level 2'),
        ('TR2Sq1Se3', 'Tango Romantica Sequence 2 Section 1 Level 3'),
        ('TR2Sq1Se4', 'Tango Romantica Sequence 2 Section 1 Level 4'),
        ('TR2Sq2Se', 'Tango Romantica Sequence 2 Section 2'),
        ('TR2Sq2Se1', 'Tango Romantica Sequence 2 Section 2 Level 1'),
        ('TR2Sq2Se2', 'Tango Romantica Sequence 2 Section 2 Level 2'),
        ('TR2Sq2Se3', 'Tango Romantica Sequence 2 Section 2 Level 3'),
        ('TR2Sq2Se4', 'Tango Romantica Sequence 2 Section 2 Level 4'),
        ('BL1Sq', 'Blues Sequence 1'),
        ('BL1Sq1', 'Blues Sequence 1 Level 1'),
        ('BL1Sq2', 'Blues Sequence 1 Level 2'),
        ('BL1Sq3', 'Blues Sequence 1 Level 3'),
        ('BL1Sq4', 'Blues Sequence 1 Level 4'),
        ('BL2Sq', 'Blues Sequence 2'),
        ('BL2Sq1', 'Blues Sequence 2 Level 1'),
        ('BL2Sq2', 'Blues Sequence 2 Level 2'),
        ('BL2Sq3', 'Blues Sequence 2 Level 3'),
        ('BL2Sq4', 'Blues Sequence 2 Level 4'),
        ('BL3Sq', 'Blues Sequence 3'),
        ('BL3Sq1', 'Blues Sequence 3 Level 1'),
        ('BL3Sq2', 'Blues Sequence 3 Level 2'),
        ('BL3Sq3', 'Blues Sequence 3 Level 3'),
        ('BL3Sq4', 'Blues Sequence 3 Level 4'),
        ('MB1Sq1Se', 'Midnight Blues Sequence 1 Section 1'),
        ('MB1Sq1Se1', 'Midnight Blues Sequence 1 Section 1 Level 1'),
        ('MB1Sq1Se2', 'Midnight Blues Sequence 1 Section 1 Level 2'),
        ('MB1Sq1Se3', 'Midnight Blues Sequence 1 Section 1 Level 3'),
        ('MB1Sq1Se4', 'Midnight Blues Sequence 1 Section 1 Level 4'),
        ('MB1Sq2Se', 'Midnight Blues Sequence 1 Section 2'),
        ('MB1Sq2Se1', 'Midnight Blues Sequence 1 Section 2 Level 1'),
        ('MB1Sq2Se2', 'Midnight Blues Sequence 1 Section 2 Level 2'),
        ('MB1Sq2Se3', 'Midnight Blues Sequence 1 Section 2 Level 3'),
        ('MB1Sq2Se4', 'Midnight Blues Sequence 1 Section 2 Level 4'),
        ('MB2Sq1Se', 'Midnight Blues Sequence 2 Section 1'),
        ('MB2Sq1Se1', 'Midnight Blues Sequence 2 Section 1 Level 1'),
        ('MB2Sq1Se2', 'Midnight Blues Sequence 2 Section 1 Level 2'),
        ('MB2Sq1Se3', 'Midnight Blues Sequence 2 Section 1 Level 3'),
        ('MB2Sq1Se4', 'Midnight Blues Sequence 2 Section 1 Level 4'),
        ('MB2Sq2Se', 'Midnight Blues Sequence 2 Section 2'),
        ('MB2Sq2Se1', 'Midnight Blues Sequence 2 Section 2 Level 1'),
        ('MB2Sq2Se2', 'Midnight Blues Sequence 2 Section 2 Level 2'),
        ('MB2Sq2Se3', 'Midnight Blues Sequence 2 Section 2 Level 3'),
        ('MB2Sq2Se4', 'Midnight Blues Sequence 2 Section 2 Level 4'),
        ('1BL', 'Blues Pattern Dance Sequence 1'),
        ('1BL1', 'Blues Pattern Dance Sequence 1 Level 1'),
        ('1BL2', 'Blues Pattern Dance Sequence 1 Level 2'),
        ('1BL3', 'Blues Pattern Dance Sequence 1 Level 3'),
        ('1BL4', 'Blues Pattern Dance Sequence 1 Level 4'),
        ('2BL', 'Blues Pattern Dance Sequence 2'),
        ('2BL1', 'Blues Pattern Dance Sequence 2 Level 1'),
        ('2BL2', 'Blues Pattern Dance Sequence 2 Level 2'),
        ('2BL3', 'Blues Pattern Dance Sequence 2 Level 3'),
        ('2BL4', 'Blues Pattern Dance Sequence 2 Level 4'),
        ('1YP', 'Yankee Polka Pattern Dance Section 1'),
        ('1YP1', 'Yankee Polka Pattern Dance Section 1 Level 1'),
        ('1YP2', 'Yankee Polka Pattern Dance Section 1 Level 2'),
        ('1YP3', 'Yankee Polka Pattern Dance Section 1 Level 3'),
        ('1YP4', 'Yankee Polka Pattern Dance Section 1 Level 4'),
        ('2YP', 'Yankee Polka Pattern Dance Section 2'),
        ('2YP1', 'Yankee Polka Pattern Dance Section 2 Level 1'),
        ('2YP2', 'Yankee Polka Pattern Dance Section 2 Level 2'),
        ('2YP3', 'Yankee Polka Pattern Dance Section 2 Level 3'),
        ('2YP4', 'Yankee Polka Pattern Dance Section 2 Level 4'),
        ('GW1Se1', 'GW1Se1'),
        ('GW1Se2', 'GW1Se2'),
        ('GW1Se3', 'GW1Se3'),
        ('GW1Se4', 'GW1Se4'),
        ('GW2Se1', 'GW2Se1'),
        ('GW2Se2', 'GW2Se2'),
        ('GW2Se3', 'GW2Se3'),
        ('GW2Se4', 'GW2Se4'),
        ('R1Sq1', 'R1Sq1'),
        ('R1Sq2', 'R1Sq2'),
        ('R1Sq3', 'R1Sq3'),
        ('R1Sq4', 'R1Sq4'),
        ('R2Sq1', 'R2Sq1'),
        ('R2Sq2', 'R2Sq2'),
        ('R2Sq3', 'R2Sq3'),
        ('R2Sq4', 'R2Sq4'),
        ('Sp', 'Dance Spin'),
        ('Sp1', 'Dance Spin Level 1'),
        ('Sp2', 'Dance Spin Level 2'),
        ('Sp3', 'Dance Spin Level 3'),
        ('Sp4', 'Dance Spin Level 4'),
        ('StaLi', 'Dance Stationary Lift'),
        ('StaLi1', 'Dance Stationary Lift Level 1'),
        ('StaLi2', 'Dance Stationary Lift Level 2'),
        ('StaLi3', 'Dance Stationary Lift Level 3'),
        ('StaLi4', 'Dance Stationary Lift Level 4'),
        ('SILi', 'Dance Straight Line Lift'),
        ('SILi1', 'Dance Straight Line Lift Level 1'),
        ('SILi2', 'Dance Straight Line Lift Level 2'),
        ('SILi3', 'Dance Straight Line Lift Level 3'),
        ('SILi4', 'Dance Straight Line Lift Level 4'),
        ('CuLi', 'Dance Curve Lift'),
        ('CuLi1', 'Dance Curve Lift Level 1'),
        ('CuLi2', 'Dance Curve Lift Level 2'),
        ('CuLi3', 'Dance Curve Lift Level 3'),
        ('CuLi4', 'Dance Curve Lift Level 4'),
        ('RoLi', 'Dance Rotational Lift'),
        ('RoLi1', 'Dance Rotational Lift Level 1'),
        ('RoLi2', 'Dance Rotational Lift Level 2'),
        ('RoLi3', 'Dance Rotational Lift Level 3'),
        ('RoLi4', 'Dance Rotational Lift Level 4'),
        ('SeLi', 'Dance Serpentine Lift'),
        ('SeLi1', 'Dance Serpentine Lift Level 1'),
        ('SeLi2', 'Dance Serpentine Lift Level 2'),
        ('SeLi3', 'Dance Serpentine Lift Level 3'),
        ('SeLi4', 'Dance Serpentine Lift Level 4'),
        ('RRoLi', 'Dance Reverse Rotational Lift'),
        ('RRoLi1', 'Dance Reverse Rotational Lift Level 1'),
        ('RRoLi2', 'Dance Reverse Rotational Lift Level 2'),
        ('RRoLi3', 'Dance Reverse Rotational Lift Level 3'),
        ('RRoLi4', 'Dance Reverse Rotational Lift Level 4'),
        ('SlLi', 'Stright Line Lift'),
        ('SlLiB', 'Stright Line Lift Level B'),
        ('SlLi1', 'Stright Line Lift Level 1'),
        ('SlLi2', 'Stright Line Lift Level 2'),
        ('SlLi3', 'Stright Line Lift Level 3'),
        ('SlLi4', 'Stright Line Lift Level 4'),
        ('ChLi', 'Choreographic Dance Lift'),
        ('ChLi1', 'Choreographic Dance Lift'),
        ('STw', 'Twizzles'),
        ('STw1', 'Twizzles Level 1'),
        ('STw2', 'Twizzles Level 2'),
        ('STw3', 'Twizzles Level 3'),
        ('STw4', 'Twizzles Level 4'),
        ('pSTw', 'Twizzles'),
        ('pSTw1', 'Twizzles Level 1'),
        ('pSTw2', 'Twizzles Level 2'),
        ('pSTw3', 'Twizzles Level 3'),
        ('pSTw4', 'Twizzles Level 4'),
        ('NtMiTw', 'No Touch Midline Twizzles'),
        ('NtMiTwB', 'No Touch Midline Twizzles Level B'),
        ('NtMiTw1', 'No Touch Midline Twizzles Level 1'),
        ('NtMiTw2', 'No Touch Midline Twizzles Level 2'),
        ('NtMiTw3', 'No Touch Midline Twizzles Level 3'),
        ('NtMiTw4', 'No Touch Midline Twizzles Level 4'),
        ('SqTw', 'Sq Twizzles'),
        ('SqTwB', 'Sq Twizzles Level B'),
        ('SqTw1', 'Sq Twizzles Level 1'),
        ('SqTw2', 'Sq Twizzles Level 2'),
        ('SqTw3', 'Sq Twizzles Level 3'),
        ('SqTw4', 'Sq Twizzles Level 4'),
        ('MiSt', 'Midline Step Sequence in Hold'),
        ('MiSt1', 'Midline Step Sequence in Hold Level 1'),
        ('MiSt2', 'Midline Step Sequence in Hold Level 2'),
        ('MiSt3', 'Midline Step Sequence in Hold Level 3'),
        ('MiSt4', 'Midline Step Sequence in Hold Level 4'),
        ('DiSt', 'Diagonal Step Sequence in Hold'),
        ('DiSt1', 'Diagonal Step Sequence in Hold Level 1'),
        ('DiSt2', 'Diagonal Step Sequence in Hold Level 2'),
        ('DiSt3', 'Diagonal Step Sequence in Hold Level 3'),
        ('DiSt4', 'Diagonal Step Sequence in Hold Level 4'),
        ('NtDiSt', 'Nt Diagonal Step Sequence in Hold'),
        ('NtDiSt1', 'Nt Diagonal Step Sequence in Hold Level 1'),
        ('NtDiSt2', 'Nt Diagonal Step Sequence in Hold Level 2'),
        ('NtDiSt3', 'Nt Diagonal Step Sequence in Hold Level 3'),
        ('NtDiSt4', 'Nt Diagonal Step Sequence in Hold Level 4'),
        ('NtMiSt', 'Not Touching Midline Step Sequence'),
        ('NtMiSt1', 'Not Touching Midline Step Sequence Level 1'),
        ('NtMiSt2', 'Not Touching Midline Step Sequence Level 2'),
        ('NtMiSt3', 'Not Touching Midline Step Sequence Level 3'),
        ('NtMiSt4', 'Not Touching Midline Step Sequence Level 4'),
        ('NtCiSt', 'Not Touching Circular Step Sequence'),
        ('NtCiSt1', 'Not Touching Circular Step Sequence Level 1'),
        ('NtCiSt2', 'Not Touching Circular Step Sequence Level 2'),
        ('NtCiSt3', 'Not Touching Circular Step Sequence Level 3'),
        ('NtCiSt4', 'Not Touching Circular Step Sequence Level 4'),
        ('MiStNt', 'Not Touching Midline Step Sequence'),
        ('MiStNtB', 'Not Touching Midline Step Sequence Level B'),
        ('MiStNt1', 'Not Touching Midline Step Sequence Level 1'),
        ('MiStNt2', 'Not Touching Midline Step Sequence Level 2'),
        ('MiStNt3', 'Not Touching Midline Step Sequence Level 3'),
        ('MiStNt4', 'Not Touching Midline Step Sequence Level 4'),
        ('1S1', '1S1'),
        ('1S2', '1S2'),
        ('1S3', '1S3'),
        ('1S4', '1S4'),
        ('2S1', '2S1'),
        ('2S2', '2S2'),
        ('2S3', '2S3'),
        ('2S4', '2S4'),
        ('3S1', '3S1'),
        ('3S2', '3S2'),
        ('3S3', '3S3'),
        ('3S4', '3S4'),
        ('4S1', '4S1'),
        ('4S2', '4S2'),
        ('4S3', '4S3'),
        ('4S4', '4S4'),
        ('5S1', '5S1'),
        ('5S2', '5S2'),
        ('5S3', '5S3'),
        ('5S4', '5S4'),
        ('6S1', '6S1'),
        ('6S2', '6S2'),
        ('6S3', '6S3'),
        ('6S4', '6S4'),
        ('1S11', '1S1'),
        ('1S21', '1S2'),
        ('1S31', '1S3'),
        ('1S41', '1S4'),
        ('2S11', '2S1'),
        ('2S21', '2S2'),
        ('2S31', '2S3'),
        ('2S41', '2S4'),
        ('3S11', '3S1'),
        ('3S21', '3S2'),
        ('3S31', '3S3'),
        ('3S41', '3S4'),
        ('4S11', '4S1'),
        ('4S21', '4S2'),
        ('4S31', '4S3'),
        ('4S41', '4S4'),
        ('1S12', '1S1'),
        ('1S22', '1S2'),
        ('1S32', '1S3'),
        ('1S42', '1S4'),
        ('2S12', '2S1'),
        ('2S22', '2S2'),
        ('2S32', '2S3'),
        ('2S42', '2S4'),
        ('3S12', '3S1'),
        ('3S22', '3S2'),
        ('3S32', '3S3'),
        ('3S42', '3S4'),
        ('4S12', '4S1'),
        ('4S22', '4S2'),
        ('4S32', '4S3'),
        ('4S42', '4S4'),
        ('1S13', '1S1'),
        ('1S23', '1S2'),
        ('1S33', '1S3'),
        ('1S43', '1S4'),
        ('2S13', '2S1'),
        ('2S23', '2S2'),
        ('2S33', '2S3'),
        ('2S43', '2S4'),
        ('3S13', '3S1'),
        ('3S23', '3S2'),
        ('3S33', '3S3'),
        ('3S43', '3S4'),
        ('4S13', '4S1'),
        ('4S23', '4S2'),
        ('4S33', '4S3'),
        ('4S43', '4S4'),
        ('1S14', '1S1'),
        ('1S24', '1S2'),
        ('1S34', '1S3'),
        ('1S44', '1S4'),
        ('2S14', '2S1'),
        ('2S24', '2S2'),
        ('2S34', '2S3'),
        ('2S44', '2S4'),
        ('3S14', '3S1'),
        ('3S24', '3S2'),
        ('3S34', '3S3'),
        ('3S44', '3S4'),
        ('4S14', '4S1'),
        ('4S24', '4S2'),
        ('4S34', '4S3'),
        ('4S44', '4S4'),
        ('1QS1', '1QS1'),
        ('1QS2', '1QS2'),
        ('1QS3', '1QS3'),
        ('1QS4', '1QS4'),
        ('2QS1', '2QS1'),
        ('2QS2', '2QS2'),
        ('2QS3', '2QS3'),
        ('2QS4', '2QS4'),
        ('3QS1', '3QS1'),
        ('3QS2', '3QS2'),
        ('3QS3', '3QS3'),
        ('3QS4', '3QS4'),
        ('4QS1', '4QS1'),
        ('4QS2', '4QS2'),
        ('4QS3', '4QS3'),
        ('4QS4', '4QS4'),
        ('1FS1', '1FS1'),
        ('1FS2', '1FS2'),
        ('1FS3', '1FS3'),
        ('1FS4', '1FS4'),
        ('2FS1', '2FS1'),
        ('2FS2', '2FS2'),
        ('2FS3', '2FS3'),
        ('2FS4', '2FS4'),
        ('3FS1', '3FS1'),
        ('3FS2', '3FS2'),
        ('3FS3', '3FS3'),
        ('3FS4', '3FS4'),
        ('4FS1', '4FS1'),
        ('4FS2', '4FS2'),
        ('4FS3', '4FS3'),
        ('4FS4', '4FS4'),
        ('Li', 'Transition Lift'),
        ('ChSp', 'ChSp'),
        ('ChSp1', 'ChSp1'),
        ('ChSt', 'ChSt'),
        ('ChSt1', 'ChSt1'),
        ('sq','sq'),
        ('GW1Se', 'GW1Se'),
        ('GW2Se', 'GW2Se'),
        ('SpSt', 'SpSt'),
        ('SpSt1', 'SpSt1'),
        ('SpSt2', 'SpSt2'),
        ('SpSt3', 'SpSt3'),
        ('SpSt4', 'SpSt4'),
        ('FSTw', 'FSTw'),
        ('FSTw1', 'FSTw1'),
        ('FSTw2', 'FSTw2'),
        ('FSTw3', 'FSTw3'),
        ('FSTw4', 'FSTw4'),
        ('CSeSt', 'CSeSt'),
        ('CSeSt1', 'CSeSt1'),
        ('CSeSt2', 'CSeSt2'),
        ('CSeSt3', 'CSeSt3'),
        ('CSeSt4', 'CSeSt4'),
        ('BSTw', 'BSTw'),
        ('BSTw1', 'BSTw1'),
        ('BSTw2', 'BSTw2'),
        ('BSTw3', 'BSTw3'),
        ('BSTw4', 'BSTw4'),
        ('CCiSt', 'CCiSt'),
        ('CCiSt1', 'CCiSt1'),
        ('CCiSt2', 'CCiSt2'),
        ('CCiSt3', 'CCiSt3'),
        ('CCiSt4', 'CCiSt4'),
        ('S3', 'S3'),
        ('S4', 'S4'),
        ('ACiSt1', 'ACiSt1'),
        ('5Li1', '5Li1'),
        ('5Li2', '5Li2')
    )


    element_name = models.CharField(max_length = 10,
                                    choices = BASE_ELEMENT_CHOICES,
                                    unique=True)

    class Meta:
        app_label = 'statsonice'
    def __unicode__(self):
        return u'(BaseElement %s)' % (self.element_name)
    def clean(self):
        EnumValidator.validate_enum(self.element_name, BaseElement.BASE_ELEMENT_CHOICES)
    def save(self, *args, **kwargs):
        self.full_clean()
        super(BaseElement, self).save(*args, **kwargs)

